(function(){'use strict';
var g,h="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},k="object"===typeof h.global&&h.global?h.global:"object"===typeof global&&global&&global.Object===Object?global:this;h.global=k;var aa="object"===typeof h.exportsNamespace&&h.exportsNamespace?h.exportsNamespace:k;h.exportsNamespace=aa;k.Object.freeze(h);var ba={envInfo:h,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.13"};k.Object.freeze(ba);k.Object.freeze(ba.semantics);
var n=k.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=k.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=k.WeakMap?new k.WeakMap:null;function q(a){return function(b,c){return!(!b||!b.b||b.b.C!==c||b.b.A!==a)}}function fa(a){for(var b in a)return b}
function ga(a,b,c){var d=new a.ja(b[c]);if(c<b.length-1){a=a.E;c+=1;for(var f=d.ea,l=0;l<f.length;l++)f[l]=ga(a,b,c)}return d}function ha(a){return void 0===a?"undefined":a.toString()}
function ia(a){switch(typeof a){case "string":return r(ja);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?r(ka):b<<16>>16===b&&1/b!==1/-0?r(la):r(ma):"number"===typeof a?r(na):r(oa);case "boolean":return r(pa);case "undefined":return r(qa);default:return null===a?a.Ab():ra(a)?r(sa):a&&a.b?r(a.b):null}}
function ta(a){switch(typeof a){case "string":return ua(t(),a);case "number":return va(wa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.b||null===a?a.p():null===ea?42:xa(a)}}function u(a){return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}function ya(a,b){var c=k.Object.getPrototypeOf,d=k.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}
function za(a,b,c){a=ya(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function Aa(a,b,c,d){a=ya(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new k.TypeError("super has no setter '"+c+"'.");}
var xa=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ta(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.b){var b=a.$idHashCode$0;if(void 0!==b)return b;if(k.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:ta(a)};this.__ScalaJSExportsNamespace=aa;
function v(){this.S=this.ja=void 0;this.A=this.E=this.l=null;this.C=0;this.ga=null;this.P="";this.k=this.N=this.O=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function w(a,b,c){var d=new v;d.l={};d.E=null;d.ga=a;d.P=b;d.k=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function x(a,b,c,d,f,l,e){var m=new v,p=fa(a);l=l||function(a){return!!(a&&a.b&&a.b.l[p])};e=e||function(a,b){return!!(a&&a.b&&a.b.C===b&&a.b.A.l[p])};m.S=f;m.l=c;m.P="L"+b+";";m.k=e;m.name=b;m.isInterface=!1;m.isRawJSType=!!d;m.isInstance=l;return m}
function Ba(a){function b(a){if("number"===typeof a){this.ea=Array(a);for(var b=0;b<a;b++)this.ea[b]=f}else this.ea=a}var c=new v,d=a.ga,f="longZero"==d?y().M:d;b.prototype=new z;b.prototype.constructor=b;b.prototype.b=c;var d="["+a.P,l=a.A||a,e=a.C+1;c.ja=b;c.S=Ca;c.l={c:1,Ra:1,e:1};c.E=a;c.A=l;c.C=e;c.ga=null;c.P=d;c.O=void 0;c.N=void 0;c.k=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return l.k(a,e)};return c}
function r(a){if(!a.O){var b=new A;b.u=a;a.O=b}return a.O}v.prototype.getFakeInstance=function(){return this===ja?"some string":this===pa?!1:this===ka||this===la||this===ma||this===na||this===oa?0:this===sa?y().M:this===qa?void 0:{b:this}};v.prototype.getSuperclass=function(){return this.S?r(this.S):null};v.prototype.getComponentType=function(){return this.E?r(this.E):null};v.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.N||(b.N=Ba(b)),b=b.N;return ga(b,a,0)};
var Da=w(!1,"Z","boolean"),Ea=w(0,"C","char"),Fa=w(0,"B","byte"),Ga=w(0,"S","short"),Ha=w(0,"I","int"),Ia=w("longZero","J","long"),Ja=w(0,"F","float"),Ka=w(0,"D","double");Da.k=q(Da);Ea.k=q(Ea);Fa.k=q(Fa);Ga.k=q(Ga);Ha.k=q(Ha);Ia.k=q(Ia);Ja.k=q(Ja);Ka.k=q(Ka);function B(){}function z(){}z.prototype=B.prototype;B.prototype.f=function(){return this};B.prototype.h=function(){var a=ia(this).u.name,b=(+(this.p()>>>0)).toString(16);return a+"@"+b};B.prototype.p=function(){return xa(this)};B.prototype.toString=function(){return this.h()};var Ca=x({c:0},"java.lang.Object",{c:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.b){var c=a.C||0;return!(c<b)&&(c>b||!a.A.isPrimitive)}return!1});B.prototype.b=Ca;
function La(a,b,c){var d=Ma(!0);Na(b.n,c);a.X(Oa(function(a,b,c,d){return function(a){if(b.a)Pa(c,a),b.a=!1;else return Na(c.n,d),Pa(c,a)}}(a,d,b,",")));Na(b.n,")");return b}function C(){}C.prototype=new z;C.prototype.constructor=C;C.prototype.f=function(){return this};
function Qa(a){var b=(new D).q(null),c=a.getContext("2d");a.width=a.parentElement.clientWidth|0;a.height=a.parentElement.clientHeight|0;c.fillStyle="#f8f8f8";c.fillRect(0,0,a.width|0,a.height|0);c.fillStyle="black";var d=Ma(!1);E(0,b);var f=(new F).q(G(-1,-4));E(0,b);var l=(new F).q(G(1,-2));E(0,b);var e=(new F).q(G(3,16)),m=Ra();a.onmousedown=function(a,b,c,d,f){return function(e){E(H(),f);b.a=G(+e.clientX,+e.clientY);E(H(),f);c.a=G(+e.clientX,+e.clientY);E(H(),f);d.a=G(+e.clientX,+e.clientY);a.a=
!0}}(d,f,l,e,b);a.onmouseup=function(a){return function(){a.a=!1}}(d);a.onmousemove=function(a){return function(b){return a.z(b)}}(Sa(a,c,d,f,l,e,m,b))}function Ta(a,b,c,d){return(c.a.d*b.a.g-b.a.d*c.a.g)/(c.a.d-b.a.d)+Ua(0,b,c,d)*b.a.d*c.a.d}function E(a,b){null===b.a&&null===b.a&&(a=new I,a.L=b,b.a=a)}function Ua(a,b,c,d){return(d.a.g-(d.a.d*(c.a.g-b.a.g)+c.a.d*b.a.g-b.a.d*c.a.g)/(c.a.d-b.a.d))/(d.a.d*(d.a.d-b.a.d-c.a.d)+b.a.d*c.a.d)}
function Va(a,b,c,d){return(c.a.g-b.a.g)/(c.a.d-b.a.d)-Ua(0,b,c,d)*(b.a.d+c.a.d)}C.prototype.main=function(a){Qa(a)};C.prototype.b=x({Da:0},"sketcher.ScratchPad$",{Da:1,c:1});var Wa=void 0;function H(){Wa||(Wa=(new C).f());return Wa}aa.sketcher=aa.sketcher||{};aa.sketcher.ScratchPad=H;function A(){this.u=null}A.prototype=new z;A.prototype.constructor=A;A.prototype.h=function(){return(this.u.isInterface?"interface ":this.u.isPrimitive?"":"class ")+this.u.name};
A.prototype.b=x({Qa:0},"java.lang.Class",{Qa:1,c:1});function J(){this.va=null}J.prototype=new z;J.prototype.constructor=J;J.prototype.f=function(){Xa=this;this.va=Ya(!1);Ya(!0);return this};J.prototype.b=x({cb:0},"java.lang.System$",{cb:1,c:1});var Xa=void 0;function K(){}K.prototype=new z;K.prototype.constructor=K;function Za(){}Za.prototype=K.prototype;K.prototype.Z=function(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);return a^b};
K.prototype.I=function(a,b){a=this.Z(a,b);return-430675100+n(5,a<<13|a>>>19|0)|0};K.prototype.F=function(a,b){a^=b;a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};function $a(a,b,c){var d=(new L).G(0);c=(new L).G(c);b.X(Oa(function(a,b,c){return function(d){c.a=a.I(c.a,ab(bb(),d));b.a=1+b.a|0}}(a,d,c)));return a.F(c.a,d.a)}function M(){this.s=!1;this.na=this.R=this.B=null;this.V=!1;this.ua=this.pa=0}M.prototype=new z;M.prototype.constructor=M;
M.prototype.f=function(){cb=this;this.B=(this.s=!!(k.ArrayBuffer&&k.Int32Array&&k.Float32Array&&k.Float64Array))?new k.ArrayBuffer(8):null;this.R=this.s?new k.Int32Array(this.B,0,2):null;this.s&&new k.Float32Array(this.B,0,2);this.na=this.s?new k.Float64Array(this.B,0,1):null;if(this.s)this.R[0]=16909060,a=1===((new k.Int8Array(this.B,0,8))[0]|0);else var a=!0;this.pa=(this.V=a)?0:1;this.ua=this.V?1:0;return this};
function va(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.s)a.na[0]=b,a=(new N).H(a.R[a.ua]|0,a.R[a.pa]|0);else{if(b!==b)a=!1,b=2047,c=+k.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+k.Math.pow(2,-1022)){b=+k.Math.pow(2,52);var c=+k.Math.log(d)/.6931471805599453,c=+k.Math.floor(c)|0,c=1023>c?c:1023,f=d/+k.Math.pow(2,c)*b,d=+k.Math.floor(f),f=f-d,d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/b&&(c=1+c|0,d=1);
1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+k.Math.pow(2,-1074),c=+k.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new N).H(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.x^a.w}M.prototype.b=x({jb:0},"scala.scalajs.runtime.Bits$",{jb:1,c:1});var cb=void 0;function wa(){cb||(cb=(new M).f());return cb}function O(){}O.prototype=new z;O.prototype.constructor=O;O.prototype.f=function(){return this};function db(a,b){return null===b?"null":ha(b)}
function ua(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+n(65535&(b.charCodeAt(d)|0),c)|0,c=n(31,c),d=-1+d|0;return a}O.prototype.b=x({lb:0},"scala.scalajs.runtime.RuntimeString$",{lb:1,c:1});var eb=void 0;function t(){eb||(eb=(new O).f());return eb}function P(){}P.prototype=new z;P.prototype.constructor=P;P.prototype.f=function(){return this};P.prototype.b=x({mb:0},"scala.scalajs.runtime.package$",{mb:1,c:1});var fb=void 0;function Q(){}Q.prototype=new z;Q.prototype.constructor=Q;
Q.prototype.f=function(){return this};function ab(a,b){if(null===b)return 0;if(b&&b.b&&b.b.l.r||"number"===typeof b){if("number"===typeof b)return a=+b,gb(R(),a);if(ra(b))return b=null===b?y().M:b,a=b.x,b=b.w,R(),b=(new N).H(a,b),a=b.x,b=b.w,b===a>>31?a:a^b}return ta(b)}Q.prototype.b=x({tb:0},"scala.runtime.ScalaRunTime$",{tb:1,c:1});var hb=void 0;function bb(){hb||(hb=(new Q).f());return hb}function ib(){}ib.prototype=new z;ib.prototype.constructor=ib;g=ib.prototype;g.f=function(){return this};
g.Z=function(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);return a^b};function gb(a,b){a=u(b);if(a===b)return a;a=y();var c;if(-9223372036854775808>b)a.U=-2147483648,c=0;else if(0x7fffffffffffffff<=b)a.U=2147483647,c=-1;else{c=b|0;var d=b/4294967296|0;a.U=0>b&&0!==c?-1+d|0:d}a=a.U;y();return(0>a?-(4294967296*+((0!==c?~a:-a|0)>>>0)+ +((-c|0)>>>0)):4294967296*a+ +(c>>>0))===b?c^a:va(wa(),b)}g.I=function(a,b){a=this.Z(a,b);return-430675100+n(5,a<<13|a>>>19|0)|0};
g.F=function(a,b){a^=b;a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)};g.b=x({vb:0},"scala.runtime.Statics$",{vb:1,c:1});var jb=void 0;function R(){jb||(jb=(new ib).f());return jb}function lb(){}lb.prototype=new z;lb.prototype.constructor=lb;function mb(){}mb.prototype=lb.prototype;function S(){this.y=null}S.prototype=new z;S.prototype.constructor=S;function nb(){}nb.prototype=S.prototype;
S.prototype.ma=function(){if(void 0===k.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(fb||(fb=(new P).f()),a=b&&b.b&&b.b.l.ta?b:(new ob).q(b),null!==a)if(a&&a.b&&a.b.l.da)a=a.v;else throw fb||(fb=(new P).f()),a&&a.b&&a.b.l.da?a.v:a;else throw b;}this.stackdata=a}else k.Error.captureStackTrace(this),this.stackdata=this;return this};S.prototype.oa=function(){return this.y};S.prototype.h=function(){var a=ia(this).u.name,b=this.oa();return null===b?a:a+": "+b};
S.prototype.qa=function(a){this.y=a;this.ma();return this};function T(){this.ca=0}T.prototype=new Za;T.prototype.constructor=T;T.prototype.f=function(){pb=this;this.ca=ua(t(),"Seq");ua(t(),"Map");ua(t(),"Set");return this};T.prototype.b=x({eb:0},"scala.util.hashing.MurmurHash3$",{eb:1,Fb:1,c:1});var pb=void 0;function qb(){pb||(pb=(new T).f());return pb}function rb(){}rb.prototype=new z;rb.prototype.constructor=rb;function sb(){}sb.prototype=rb.prototype;rb.prototype.h=function(){return"\x3cfunction1\x3e"};
function tb(){}tb.prototype=new z;tb.prototype.constructor=tb;function ub(){}ub.prototype=tb.prototype;function U(){this.a=!1}U.prototype=new z;U.prototype.constructor=U;U.prototype.h=function(){return""+this.a};function Ma(a){var b=new U;b.a=a;return b}U.prototype.b=x({ob:0},"scala.runtime.BooleanRef",{ob:1,c:1,e:1});var qa=x({pb:0},"scala.runtime.BoxedUnit",{pb:1,c:1,e:1},void 0,void 0,function(a){return void 0===a});function V(){this.a=0}V.prototype=new z;V.prototype.constructor=V;
function Ra(){var a=new V;a.a=1;return a}V.prototype.h=function(){return""+this.a};V.prototype.b=x({qb:0},"scala.runtime.DoubleRef",{qb:1,c:1,e:1});function L(){this.a=0}L.prototype=new z;L.prototype.constructor=L;L.prototype.h=function(){return""+this.a};L.prototype.G=function(a){this.a=a;return this};L.prototype.b=x({rb:0},"scala.runtime.IntRef",{rb:1,c:1,e:1});function F(){this.a=null}F.prototype=new z;F.prototype.constructor=F;F.prototype.h=function(){return db(t(),this.a)};
F.prototype.q=function(a){this.a=a;return this};F.prototype.b=x({sb:0},"scala.runtime.ObjectRef",{sb:1,c:1,e:1});function D(){this.a=null}D.prototype=new z;D.prototype.constructor=D;D.prototype.h=function(){return db(t(),this.a)};D.prototype.q=function(a){this.a=a;return this};D.prototype.b=x({wb:0},"scala.runtime.VolatileObjectRef",{wb:1,c:1,e:1});function vb(){}vb.prototype=new z;vb.prototype.constructor=vb;function wb(){}wb.prototype=vb.prototype;
var pa=x({Na:0},"java.lang.Boolean",{Na:1,c:1,e:1,m:1},void 0,void 0,function(a){return"boolean"===typeof a});function W(){this.fa=0}W.prototype=new z;W.prototype.constructor=W;W.prototype.h=function(){return k.String.fromCharCode(this.fa)};function xb(a){var b=new W;b.fa=a;return b}W.prototype.p=function(){return this.fa};W.prototype.b=x({Pa:0},"java.lang.Character",{Pa:1,c:1,e:1,m:1});function yb(){this.y=null}yb.prototype=new nb;yb.prototype.constructor=yb;function zb(){}zb.prototype=yb.prototype;
function Ab(){this.la=null}Ab.prototype=new sb;Ab.prototype.constructor=Ab;Ab.prototype.z=function(a){return(0,this.la)(a)};function Oa(a){var b=new Ab;b.la=a;return b}Ab.prototype.b=x({ib:0},"scala.scalajs.runtime.AnonFunction1",{ib:1,nb:1,c:1,ha:1});function Bb(){this.U=0;this.M=null}Bb.prototype=new z;Bb.prototype.constructor=Bb;Bb.prototype.f=function(){Cb=this;this.M=(new N).H(0,0);return this};
function Db(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,l=a,e=b;for(a=b=0;0<=c&&0!==(-2097152&e);){var m=l,p=e,Rb=f,kb=d;if(p===kb?(-2147483648^m)>=(-2147483648^Rb):(-2147483648^p)>=(-2147483648^kb))m=e,p=d,e=l-f|0,m=(-2147483648^e)>(-2147483648^l)?-1+(m-p|0)|0:m-p|0,l=e,e=m,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;m=d>>>1|0;f=f>>>1|0|d<<31;d=m}c=e;if(0===c?-1147483648<=(-2147483648^
l):-2147483648<=(-2147483648^c))c=4294967296*e+ +(l>>>0),l=c/1E9,f=l/4294967296|0,d=b,b=l=d+(l|0)|0,a=(-2147483648^l)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,c%=1E9,l=c|0,e=c/4294967296|0;b=[b,a,l,e];a=""+(b["2"]|0);return""+(4294967296*(b["1"]|0)+ +((b["0"]|0)>>>0))+"000000000".substring(a.length|0)+a}Bb.prototype.b=x({kb:0},"scala.scalajs.runtime.RuntimeLong$",{kb:1,c:1,K:1,e:1});var Cb=void 0;function y(){Cb||(Cb=(new Bb).f());return Cb}function Eb(){}Eb.prototype=new wb;Eb.prototype.constructor=Eb;
function Fb(){}Fb.prototype=Eb.prototype;Eb.prototype.Ja=function(){return this};
var ja=x({Ha:0},"java.lang.String",{Ha:1,c:1,e:1,sa:1,m:1},void 0,void 0,function(a){return"string"===typeof a}),ka=x({Oa:0},"java.lang.Byte",{Oa:1,r:1,c:1,e:1,m:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),oa=x({Sa:0},"java.lang.Double",{Sa:1,r:1,c:1,e:1,m:1},void 0,void 0,function(a){return"number"===typeof a}),na=x({Ua:0},"java.lang.Float",{Ua:1,r:1,c:1,e:1,m:1},void 0,void 0,function(a){return"number"===typeof a}),ma=x({Wa:0},"java.lang.Integer",{Wa:1,r:1,c:1,e:1,m:1},void 0,
void 0,function(a){return(a|0)===a&&1/a!==1/-0});function Gb(){}Gb.prototype=new wb;Gb.prototype.constructor=Gb;Gb.prototype.f=function(){return this};Gb.prototype.b=x({Ya:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Ya:1,Ca:1,c:1,Aa:1,Ba:1});var sa=x({Za:0},"java.lang.Long",{Za:1,r:1,c:1,e:1,m:1},void 0,void 0,function(a){return ra(a)});function Hb(){this.y=null}Hb.prototype=new zb;Hb.prototype.constructor=Hb;function Ib(){}Ib.prototype=Hb.prototype;
var la=x({ab:0},"java.lang.Short",{ab:1,r:1,c:1,e:1,m:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function X(){this.o=null}X.prototype=new z;X.prototype.constructor=X;function Na(a,b){a.o=""+a.o+(null===b?"null":b);return a}X.prototype.h=function(){return this.o};X.prototype.G=function(){X.prototype.Q.call(this,"");return this};X.prototype.Q=function(a){this.o=a;return this};X.prototype.b=x({bb:0},"java.lang.StringBuilder",{bb:1,c:1,sa:1,Ma:1,e:1});function Jb(){}
Jb.prototype=new z;Jb.prototype.constructor=Jb;function Kb(){}Kb.prototype=Jb.prototype;Jb.prototype.h=function(){return(this.t<this.W?"non-empty":"empty")+" iterator"};Jb.prototype.X=function(a){for(;this.t<this.W;)a.z(Lb(this))};function N(){this.w=this.x=0}N.prototype=new mb;N.prototype.constructor=N;g=N.prototype;g.h=function(){y();var a=this.x,b=this.w;return b===a>>31?""+a:0>b?"-"+Db(-a|0,0!==a?~b:-b|0):Db(a,b)};g.H=function(a,b){this.x=a;this.w=b;return this};
g.G=function(a){N.prototype.H.call(this,a,a>>31);return this};g.p=function(){return this.x^this.w};function ra(a){return!!(a&&a.b&&a.b.l.ya)}g.b=x({ya:0},"scala.scalajs.runtime.RuntimeLong",{ya:1,r:1,c:1,e:1,m:1});function Mb(){this.L=this.Y=this.i=this.j=this.J=this.ka=this.T=this.ia=null}Mb.prototype=new sb;Mb.prototype.constructor=Mb;
Mb.prototype.z=function(a){var b=this.j.a;this.J.a=G(b.d,b.g);b=this.i.a;this.j.a=G(b.d,b.g);b=this.i;E(H(),this.L);b.a=G(+a.clientX,+a.clientY);var c=+k.Math.abs(this.i.a.d-this.j.a.d),d=+k.Math.abs(this.i.a.g-this.j.a.g),b=+k.Math.pow(c,2)+ +k.Math.pow(d,2),f=26/+k.Math.sqrt(b),b=(this.Y.a+(6<f?6:.3>f?.3:f))/2.3;this.Y.a=b;var l=this.ia.getBoundingClientRect();if(this.ka.a){Xa||(Xa=(new J).f());var e=Xa.va;Nb(e,""+f);Nb(e,"\n");if(1.5<c){if(this.j.a.d>this.i.a.d)var e=u(10*this.i.a.d),m=u(10*this.j.a.d),
p=e>m;else e=u(10*this.j.a.d),m=u(10*this.i.a.d),p=e>m;d=e;c=1;e=(f=p)?-1+e|0:m;if(!f)for(;;){f=d;this.T.fillRect(f/10|0,Ua(H(),this.J,this.j,this.i)*f*f/100+Va(H(),this.J,this.j,this.i)*f/10+Ta(H(),this.J,this.j,this.i),b,b);if(d===e)break;d=d+c|0}}else if(1.5<d&&(this.j.a.g>this.i.a.g?(e=u(this.i.a.g),m=u(this.j.a.g)):(e=u(this.j.a.g),m=u(this.i.a.g)),p=e>m,d=e,c=1,e=(f=p)?-1+e|0:m,!f))for(;;){this.T.fillRect(this.i.a.d,d,b,b);if(d===e)break;d=d+c|0}this.T.fillRect(+a.clientX-+l.left,+a.clientY-
+l.top,b,b)}};function Sa(a,b,c,d,f,l,e,m){var p=new Mb;p.ia=a;p.T=b;p.ka=c;p.J=d;p.j=f;p.i=l;p.Y=e;p.L=m;return p}Mb.prototype.b=x({Ea:0},"sketcher.ScratchPad$$anonfun$main$3",{Ea:1,nb:1,c:1,ha:1,K:1,e:1});function Ob(){this.g=this.d=0}Ob.prototype=new z;Ob.prototype.constructor=Ob;g=Ob.prototype;g.ba=function(){return"Pos"};g.$=function(){return 2};g.aa=function(a){switch(a){case 0:return this.d;case 1:return this.g;default:throw(new Y).Q(""+a);}};
g.h=function(){bb();var a=this.wa(),b=this.ba()+"(",c=(new Z).f();return La(a,c,b).n.o};function G(a,b){var c=new Ob;c.d=a;c.g=b;return c}g.p=function(){var a=-889275714,a=R().I(a,gb(R(),this.d)),a=R().I(a,gb(R(),this.g));return R().F(a,2)};g.wa=function(){return Pb(this)};g.b=x({Fa:0},"sketcher.ScratchPad$Pos$3",{Fa:1,c:1,db:1,xa:1,K:1,e:1});function I(){this.L=null}I.prototype=new ub;I.prototype.constructor=I;I.prototype.h=function(){return"Pos"};
I.prototype.b=x({Ga:0},"sketcher.ScratchPad$Pos$4$",{Ga:1,qc:1,c:1,xb:1,K:1,e:1});function Y(){this.y=null}Y.prototype=new Ib;Y.prototype.constructor=Y;Y.prototype.Q=function(a){S.prototype.qa.call(this,a);return this};Y.prototype.b=x({Va:0},"java.lang.IndexOutOfBoundsException",{Va:1,$a:1,Ta:1,ta:1,c:1,e:1});function Qb(){this.W=this.t=0;this.za=null}Qb.prototype=new Kb;Qb.prototype.constructor=Qb;function Lb(a){var b=a.za.aa(a.t);a.t=1+a.t|0;return b}
function Pb(a){var b=new Qb;b.za=a;b.t=0;b.W=a.$();return b}Qb.prototype.b=x({ub:0},"scala.runtime.ScalaRunTime$$anon$1",{ub:1,Hb:1,c:1,Vb:1,gb:1,fb:1});function Sb(){}Sb.prototype=new Fb;Sb.prototype.constructor=Sb;function Tb(){}Tb.prototype=Sb.prototype;Sb.prototype.Ka=function(){Eb.prototype.Ja.call(this);return this};function Ub(){this.D=this.ra=null}Ub.prototype=new Tb;Ub.prototype.constructor=Ub;function Ya(a){var b=new Ub;b.ra=a;(new Gb).f();Sb.prototype.Ka.call(b);b.D="";return b}
function Nb(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.D=""+a.D+b,b="";else{var d=""+a.D+b.substring(0,c);k.console&&(a.ra&&k.console.error?k.console.error(d):k.console.log(d));a.D="";b=b.substring(1+c|0)}}}Ub.prototype.b=x({Xa:0},"java.lang.JSConsoleBasedPrintStream",{Xa:1,zb:1,yb:1,Ca:1,c:1,Aa:1,Ba:1,Ma:1});function ob(){this.v=this.y=null}ob.prototype=new Ib;ob.prototype.constructor=ob;g=ob.prototype;g.ba=function(){return"JavaScriptException"};g.$=function(){return 1};
g.ma=function(){this.stackdata=this.v;return this};g.aa=function(a){switch(a){case 0:return this.v;default:throw(new Y).Q(""+a);}};g.oa=function(){return ha(this.v)};g.q=function(a){this.v=a;S.prototype.qa.call(this,null);return this};g.p=function(){var a;a=qb();var b=this.$();if(0===b)a=this.ba(),a=ua(t(),a);else{for(var c=-889275714,d=0;d<b;)c=a.I(c,ab(bb(),this.aa(d))),d=1+d|0;a=a.F(c,b)}return a};g.wa=function(){return Pb(this)};
g.b=x({da:0},"scala.scalajs.js.JavaScriptException",{da:1,$a:1,Ta:1,ta:1,c:1,e:1,db:1,xa:1,K:1});function Vb(){}Vb.prototype=new z;Vb.prototype.constructor=Vb;function Wb(){}Wb.prototype=Vb.prototype;function Xb(){}Xb.prototype=new Wb;Xb.prototype.constructor=Xb;function Yb(){}Yb.prototype=Xb.prototype;function Zb(){}Zb.prototype=new Yb;Zb.prototype.constructor=Zb;function $b(){}$b.prototype=Zb.prototype;function ac(){}ac.prototype=new $b;ac.prototype.constructor=ac;function bc(){}bc.prototype=ac.prototype;
function Z(){this.n=null}Z.prototype=new bc;Z.prototype.constructor=Z;g=Z.prototype;g.f=function(){Z.prototype.Ia.call(this,16,"");return this};function cc(a,b){a=65535&(a.n.o.charCodeAt(b)|0);return xb(a)}g.z=function(a){a=65535&(this.n.o.charCodeAt(a|0)|0);return xb(a)};g.h=function(){return this.n.o};g.X=function(a){for(var b=0,c=this.n.o.length|0;b<c;)a.z(cc(this,b)),b=1+b|0};g.Ia=function(a,b){Z.prototype.La.call(this,Na((new X).G((b.length|0)+a|0),b));return this};
g.La=function(a){this.n=a;return this};function Pa(a,b){Na(a.n,db(t(),b));return a}g.p=function(){var a=qb();return this&&this.b&&this.b.l.fc?a.F(a.ca,0):$a(a,this,a.ca)};g.b=x({hb:0},"scala.collection.mutable.StringBuilder",{hb:1,hc:1,Ib:1,Gb:1,Jb:1,c:1,Zb:1,$b:1,ec:1,bc:1,gb:1,fb:1,Pb:1,Wb:1,Ob:1,cc:1,Tb:1,Kb:1,Lb:1,Ub:1,xa:1,Xb:1,Db:1,ha:1,Mb:1,Nb:1,Yb:1,nc:1,mc:1,pc:1,Cb:1,oc:1,jc:1,Bb:1,Ra:1,sa:1,kc:1,Qb:1,Rb:1,lc:1,gc:1,Sb:1,Eb:1,m:1,ic:1,dc:1,ac:1,K:1,e:1});
}).call(this);
//# sourceMappingURL=sketcher-opt.js.map
